### ISSUE TITLE
putty crash

### ISSUE THREAD

**Issue by itaykrk** [seastorm/PuttyRider#2] opened 2014-12-11 13:41 UTC
im trying this on windows 8.1 pro 64bit, putty 0.63
after the succsesfull injection putty just crash.

**Comment by seastorm** [comment] 2014-12-12 21:09
Please provide the following information, as I was not able to reproduce the crash:
- Did you compile PuttyRider yourself or did you use the binaries from the release?
- What options did you use to run PuttyRider?
- Please provide the output of PuttyRider.exe when starting with the following options: -p 0 -d -f
- Did you use the 'official' putty.exe 0.63 of you compiled it yourself?

Thanks,
Adrian

**Comment by itaykrk** [comment] 2014-12-14 08:40
1. yes i compiled myself, where i can find the release binaries?
2. options: -p <pid> -f
3. output:
   [+] Using putty.exe PID=2464
   [+] Injecting DLL...
   [+] Pipe client connected
   [+] [2464] Target path: C:\Users\Itayk.CYBERHAT\Downloads\putty.exe
   [+] [2464] Base address: 00400000
   [+] [2464] .text start address: 00001000
   [+] [2464] .text size: 00055fb1
   [+] [2464] ldisc_send() found at: 004083ee
   [+] [2464] term_data() found at: 004371a8
   [+] [2464] Log file created: C:\Users\Public\PuttyRider-master\PuttyRider.log.24
   64
   [+] [2464] Function hooks installed successfully
   [+] Check the log file and/or the remote connection handler
   [+] Exiting PuttyRider
4. yes i used the official

**Comment by seastorm** [comment] 2014-12-14 09:34
Thanks for the response. 
I see a potential issue here: if you compiled it as a 64-bit application, it will not work because it will try to inject into a 32-bit process (putty.exe). PuttyRider was designed as a 32-bit application.

Please test the 32-bit official binaries from here https://github.com/seastorm/PuttyRider/releases/download/0.1/PuttyRider-bin.zip and let me know if you still have the crash.

**Comment by seastorm** [comment] 2014-12-21 18:17
Fixed with https://github.com/seastorm/PuttyRider/commit/8b5707f3b2ecb3e47fd185b273ee90d4398d0d8c

**Closed as completed by seastorm** 2014-12-21 18:17 UTC
